"use client";
// import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import RecoidContextProvider from "@/components/others/RecoilContextProvider";
import RenderModal from "@/components/others/RenderModal";
import Head from "next/head";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import EndCredits from "@/components/Home/EndCredits";
import { useCallback, useState } from "react";

const montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: "/assets/img1.jpg",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [activeModal, setActiveModal] = useState("");

  const isModalActive = useCallback((modal: string) => {
    setActiveModal(modal);
  }, []);

  return (
    <html lang="en">
      <Head>
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_API}&libraries=places`}
        ></script>
      </Head>
      <body className={`${montserrat.className} ${"body"}`}>
        <RecoidContextProvider>
          <RenderModal active={isModalActive} />
          <Header />
          <div
            className="main"
            style={
              activeModal !== ""
                ? { overflow: "hidden" }
                : { overflow: "scroll" }
            }
          >
            {children}
            <Footer />
            <EndCredits text="Made With Love By Harishtaskar All Right Reserved " />
          </div>
        </RecoidContextProvider>
      </body>
    </html>
  );
}
